### ISSUE TITLE
error: running prompt: unable to set console to raw mode:

### ISSUE THREAD

**Issue by t101804** [erikgeiser/promptkit#23]
when using windows older version like windows 10 2012

**Comment by erikgeiser** [comment]
Ist this the complete error?

**Comment by erikgeiser** [comment]
I'm asking because I think the error message stems from here: https://github.com/containerd/console/blob/8f6c4e4faef5a326d2cd907097d04c0239ee5e2f/console_windows.go#L144-L146

Normally, there should be a more detailed error message after the last colon and I have no idea why it would be empty. Did you maybe set a custom `selection.Output`?

Please also note that Windows is not explicitly supported (as stated in the [README.md](https://github.com/erikgeiser/promptkit/blob/main/README.md)) due to a longstanding bug in [bubbletea](https://github.com/charmbracelet/bubbletea).
